### ISSUE TITLE
[Feature Request]Property for coin images in API

### ISSUE THREAD

**Issue by ruchern** [mrsmn/coinmarketcap#24]
Hi,

I have been looking through the API and there seemed to have one missing data that I would really wish to have. Is it possible to expose the property value for each coin images in the API?

Thank you!

**Comment by mrsmn** [comment]
Hey @ruchern,

unfortunately the coinmarketcap API doesnt' expose coin images. There is however a paid API endpoint in the works which might do so.

Cheers.

**Comment by ruchern** [comment]
@mrsmn May I know if the paid API is the one that have to request via the Google Docs form or it's an API from some other services?

**Comment by mrsmn** [comment]
It's indeed the one you have to request access to via the GDocs form. 😉

**Comment by ruchern** [comment]
@mrsmn I did sign up but have not gotten any reply. I will wait for that!
