### ISSUE TITLE
Hello Great master

### ISSUE THREAD

**Issue by usaflees** [mrsmn/coinmarketcap#27]
Im trying to install this onto my server through SSH and getting this error.  Probably a newbie mistake as im just learning.  I get this after trying to run the setup file after extraction

**Comment by mrsmn** [comment]
Hey @usaflees,

could you please state what version of Python you're using and how exactly you're trying to install the library?
You should also use pip to install ```coinmarketcap```, not setuptools.

**Comment by usaflees** [comment]
thanks for the fast reply.  Imm trying to get this script to play on my website.  Im currently using an ssh connection throuogh putty.  Ive gotten a bit further..  
![image](https://user-images.githubusercontent.com/33063257/34662846-8e3afbd2-f421-11e7-8b8f-1d24f35010e7.png)

**Comment by usaflees** [comment]
Ive changed all the permissions so that wouldnt be a problem.  Mind you I am trying to do all this without knowing basically anything.  Im using 1and1.com as hosting.

**Comment by usaflees** [comment]
I ran an ftp program to move the files into a directory on the root of my website

**Comment by usaflees** [comment]
If you are on skype or icq Id love a few minutes with you.  If not, thanks so much for the response!

**Comment by mrsmn** [comment]
You should be able to execute ```python setup.py install```.

**Comment by usaflees** [comment]
ok im further for sure.  it allowed that command, now this permission needs to be changed.  Is this server side? 
![image](https://user-images.githubusercontent.com/33063257/34663823-c44e0ce6-f426-11e7-9b22-4653dccd18d1.png)

**Comment by usaflees** [comment]
Shall i try anything else?  Is there another way I can run this on my site?  I tried taking the source code from the page on coinmarketcap.com and almost got it partly working lol.  Hours gone. =]

**Comment by mrsmn** [comment]
The permission issues you're running into are unfortunately not related to the ```coinmarketcap```library but is related to the system you're trying to install the library on.

I don't know if I can help you there, it's out of my hands.

**Comment by usaflees** [comment]
Ok, I will try to change it there.  Its trying to create a directory in the root of my database correct?

**Comment by usaflees** [comment]
I think  may have found a solution.  Im using 1and1.com as my hosting.  Its basic shared.  But Ive found an option where they will allow me to create a fresh appplication directory.  Maybe this is my answer, I will report back =]

**Comment by mrsmn** [comment]
It's trying to create the ```coinmarketcap``` directory in ```/usr/local/lib/python2.7/dist-packages``` which is read-only.

**Comment by usaflees** [comment]
alright, I changed every permission in the entire directory database.  It got as far as creating the linux db folder and I have another Core,py file now.  

![image](https://user-images.githubusercontent.com/33063257/34692082-d991b04c-f48c-11e7-8f8e-289c10498f2b.png)

**Comment by usaflees** [comment]
On phone with hosting, i think its something on their emd i cannot change without changing packages.  This wouldnt affect it would it?  thanks for the sssistance brother it means so much to me!

Enabling SSI for Linux
In order to use Server Side Includes with a Linux shared hosting package, you will need to include the following two lines somewhere in an .htaccess file within your webspace:

**Comment by usaflees** [comment]
Ok, just spent so much wasted time I believe on the phone.  I looked up the database and this root folder already exists for python as a database on my hosting.  Do I skip this part if that is the case?

**Comment by usaflees** [comment]
I know you are most likely busy, just a quick update for you where I am at.  Come to find out I need private hosting to install to root, even though I changed permissions.  I'm moving my domains to a vps now.  Good news is I downloaded visual studio and am learning ALOT.  I'm going to give some things a try tonight and maybe figure out how to get it running through the free amazon hosting with a domain of mine

**Comment by usaflees** [comment]
after a week and about 100 hours im no closer really.  Ive got my own cloud server now, and have it running in a container but still am failing getting it all to come together.  As I watch people re write this and implement it on their websites its completely discouraged me sadly.  Thanks for your help man, I appreciate it.

**Comment by mrsmn** [comment]
Sorry to hear you couldn't get it to work. 😢

**Comment by usaflees** [comment]
!!!!!! 
![Uploading **image.png…]()**

**Comment by mrsmn** [comment]
That looks promising indeed. Have a look at the README for basic instructions. Here's a summary:

- In a python interpreter, enter the following (just c/p the lines one by one)

```python
from coinmarketcap import Market
coinmarketcap = Market()
coinmarketcap.ticker(<currency>, limit=3, convert='EUR')
```
Cheers.
