### ISSUE TITLE
Store the cache data in a temporary directory rather that current working directory

### ISSUE THREAD

**Issue by jathpala** [mrsmn/coinmarketcap#30]
The current implementation stores cached data in a file called coinmarketcap_cache.sqlite in the current working directory. This is a little untidy. Given that the data is really only designed to be useful for a short period of time and it's unlikely that the user would ever want to interact with the cache file directly, would it make sense to save this file in a system temp directory instead?

I've implemented this [here](https://github.com/jathpala/coinmarketcap/commit/8f20815cc634d41a6cc45f19384e9fb38e369a3e) and would be happy to submit a pull request if it's something you would be interested in.

**Comment by jathpala** [comment]
Also, not sure but this may be a solution to the problem raised in #23 as it appears the problem was under that environment the current working directory was / which the user did not have write access to. Alternatively, it would be trivial to simply allow the user to supply a custom pathname when instantiating the Market object.

**Comment by mrsmn** [comment]
Hey there,

I'm indeed interested, I just haven't had the time to look into it as I'm quite busy IRL at the moment. If you're up for a PR, I'll be more than happy to review it.

Cheers.

**Comment by jathpala** [comment]
OK  cool. Have a look. #31

**Comment by mrsmn** [comment]
Fixed in #31 .
