### ISSUE TITLE
Support needed

### ISSUE THREAD

**Issue by achkeir** [mrsmn/coinmarketcap#35]
Hello all,

I am new to Github so not sure if this is the right way to raise an issue.

I am still beginner in python and would like to know how to run the coinmarketcap on python.

I have the Anaconda ... i typed: pip install marketcap --> successful installation --> what should be the next step ? how can i read the data or visualize it ? is it embedded in the code ?

Thanks

**Comment by mrsmn** [comment]
Hello,

please follow the intructions provided in the README:

```python
>>> from coinmarketcap import Market
>>> coinmarketcap = Market()
>>> coinmarketcap.ticker(start=0, limit=3, convert='EUR')
```
Cheers.
